icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "load"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:5) "

[[block]]
block = "temperature"
format = " $icon $average|"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10

[[block]]
block = "net"
interval = 10
format = " $icon"

[[block]]
block = "custom"
command = "echo $USER@$HOSTNAME"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %d/%m | %Hh%M') "

